package utils

import (
	"context"
	"math"
	"reflect"
	"time"

	"github.com/koordinator-sh/koord-queue/pkg/apis/scheduling/v1alpha1"
	"github.com/koordinator-sh/koord-queue/pkg/client/clientset/versioned"
	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/wait"
	"k8s.io/client-go/util/retry"
	resourcehelpers "k8s.io/component-helpers/resource"
	"k8s.io/klog/v2"

	"github.com/koordinator-sh/koord-queue/pkg/framework"
)

// indicate whether the queueunit's resource requirements are checked by the scheduler
func IsQueueUnitPodsScheduleFinished(qu *v1alpha1.QueueUnit) bool {
	switch qu.Status.Phase {
	case v1alpha1.SchedFailed, v1alpha1.SchedSucceed, v1alpha1.Enqueued, "",
		v1alpha1.Running, v1alpha1.Succeed,
		v1alpha1.Failed, v1alpha1.Dequeued, "Preempted":
		return true
	default:
		return false
	}
}

func IsQueueUnitPending(qu *v1alpha1.QueueUnit) bool {
	return qu.Status.Phase == v1alpha1.Enqueued || qu.Status.Phase == "" || qu.Status.Phase == v1alpha1.SchedFailed
}

func IsQueueUnitReservedNotRun(qu *v1alpha1.QueueUnit) bool {
	return len(qu.Status.Admissions) > 0 && !IsQueueUnitAllRunning(qu)
}

func IsQueueUnitReservedAnyResource(qu *v1alpha1.QueueUnit) bool {
	if len(qu.Status.Admissions) == 0 {
		return false
	}

	for _, ad := range qu.Status.Admissions {
		replica := ad.Replicas
		if ad.ReclaimState != nil && ad.ReclaimState.Replicas > 0 {
			replica = ad.Replicas - ad.ReclaimState.Replicas
		}
		if replica == 0 && len(ad.Resources) == 0 {
			continue
		}
		if replica > 0 {
			return true
		}

		for _, v := range ad.Resources {
			if v.CmpInt64(0) == 1 {
				return true
			}
		}
	}
	return false
}

// indicate whether the queueunits' all resource requirements are satisfied
// resource requirements are generated by job-extensions
func IsQueueUnitSatisfied(qu *v1alpha1.QueueUnit) bool {

	expectPodSet := GetQueueUnitResourceRequirementAds(qu)
	actualPodSet := GetAdmissionMap(qu)

	for n, r := range expectPodSet {
		if ad, ok := actualPodSet[n]; !ok || ad.Replicas < r.Replicas {
			return false
		}
	}
	return true
}

func IsQueueUnitAllRunning(qu *v1alpha1.QueueUnit) bool {
	if len(qu.Status.Admissions) == 0 {
		return false
	}
	for _, ad := range qu.Status.Admissions {
		if ad.Running < ad.Replicas {
			return false
		}
	}
	return true
}

func IsV1VersionDequeued(qu *v1alpha1.QueueUnit) bool {
	if len(qu.Status.Admissions) == 0 && (qu.Status.Phase == v1alpha1.Dequeued ||
		qu.Status.Phase == v1alpha1.Reserved ||
		qu.Status.Phase == v1alpha1.Running ||
		qu.Status.Phase == v1alpha1.SchedReady ||
		qu.Status.Phase == v1alpha1.SchedSucceed) {
		return true
	}
	return false
}

func IsQueueUnitAssigned(qu *v1alpha1.QueueUnit) bool {
	return len(qu.Status.Admissions) > 0 || qu.Status.Phase == v1alpha1.Running ||
		qu.Status.Phase == v1alpha1.Dequeued || qu.Status.Phase == v1alpha1.Reserved || qu.Status.Phase == v1alpha1.SchedReady
}

func IsResourceReleased(old, new *v1alpha1.QueueUnit) bool {
	oldAdmission := map[string]int64{}
	newAdmission := map[string]int64{}
	for _, ps := range old.Status.Admissions {
		oldAdmission[ps.Name] = ps.Replicas
	}
	for _, ps := range new.Status.Admissions {
		newAdmission[ps.Name] = ps.Replicas
	}
	if len(oldAdmission) != len(newAdmission) {
		// not accurate, but enough
		return true
	}
	for k, v := range oldAdmission {
		if newAdmission[k] < v {
			return true
		}
	}
	return false
}

// indicate whether the queueunit should be in the queue. queueunits are considered
// to be in the queue when their resource requirements are not satisfied.
// note that succeed and failed queueunits are not considered to be in the queue.
func IsQueueUnitDequeued(qu *v1alpha1.QueueUnit) bool {
	if IsV1VersionDequeued(qu) {
		return true
	}

	if qu.Status.Phase == v1alpha1.Succeed || qu.Status.Phase == v1alpha1.Failed {
		return true
	}

	if !IsQueueUnitSatisfied(qu) {
		return false
	}

	if IsQueueUnitAllRunning(qu) {
		return true
	}

	if len(qu.Spec.PodSets) == 0 {
		return true
	}

	return false
}

const KoordQueueDefaultRequirement = "koord-queue/default-requirement"

var DefaultReclaimProtectTime = 0 * time.Minute

func GetResourcesCanReclaim(qu *v1alpha1.QueueUnit, reclaimProtectTime time.Duration) (map[string]framework.Admission, *Resource) {
	if reclaimProtectTime > 0 && qu.Status.LastAllocateTime != nil {
		allocateTime := qu.Status.LastAllocateTime.Time
		if time.Since(allocateTime) < reclaimProtectTime {
			// protection time
			return nil, nil
		}
	}
	rps := map[string]framework.Admission{}
	for _, ps := range qu.Status.Admissions {
		if ps.Replicas == ps.Running {
			continue
		}
		if ps.ReclaimState != nil {
			continue
		}
		rps[ps.Name] = framework.Admission{
			Name:     ps.Name,
			Replicas: ps.Replicas - ps.Running,
		}
	}
	return rps, ConvertFromAdmissionToResource(qu, rps)
}

func GetQueueUnitResourceRequirementAds(qu *v1alpha1.QueueUnit) map[string]framework.Admission {
	result := map[string]framework.Admission{}
	if len(qu.Spec.PodSets) == 0 && len(qu.Spec.Request) > 0 {
		result[KoordQueueDefaultRequirement] = framework.Admission{
			Name:     KoordQueueDefaultRequirement,
			Replicas: 1,
		}
		return result
	}
	for _, ad := range qu.Spec.PodSets {
		result[ad.Name] = framework.Admission{
			Name:     ad.Name,
			Replicas: int64(ad.Count),
		}
	}
	return result
}

func ConvertFromAdmissionToResource(qu *v1alpha1.QueueUnit, ads map[string]framework.Admission) *Resource {
	converted := NewResource(nil)
	// 向前兼容一些没有podset的queueunit，只有resource的最老版本不兼容
	if _, ok := ads[KoordQueueDefaultRequirement]; ok {
		res := NewResource(qu.Spec.Request)
		converted.AddResource(res)
		return converted
	}
	for n, ad := range ads {
		for _, ps := range qu.Spec.PodSets {
			if ps.Name != n {
				continue
			}
			var copied = false
			var usedPs = &ps.Template.Spec
			for j, res := range ps.Template.Spec.Containers {
				if res.Resources.Requests == nil {
					if !copied {
						usedPs = ps.Template.Spec.DeepCopy()
						copied = true
					}
					usedPs.Containers[j].Resources.Requests = res.Resources.Limits
				}
			}
			for j, res := range ps.Template.Spec.InitContainers {
				if res.Resources.Requests == nil {
					if !copied {
						usedPs = ps.Template.Spec.DeepCopy()
						copied = true
					}
					usedPs.InitContainers[j].Resources.Requests = res.Resources.Limits
				}
			}
			specRequests := resourcehelpers.PodRequests(&v1.Pod{Spec: ps.Template.Spec}, resourcehelpers.PodResourcesOptions{})
			res := NewResource(specRequests)
			scaleUp(res, int(ad.Replicas))
			converted.Add(res.ResourceList())
			break
		}
	}
	return converted
}

func ConvertFromStatusAdmissionToResource(qu *v1alpha1.QueueUnit, ads []v1alpha1.Admission) *Resource {
	converted := NewResource(nil)
	// 向前兼容
	if IsV1VersionDequeued(qu) {
		res := NewResource(qu.Spec.Resource)
		converted.AddResource(res)
		return converted
	}
	// 向前兼容
	if len(ads) == 1 && ads[0].Name == KoordQueueDefaultRequirement {
		res := NewResource(qu.Spec.Request)
		converted.AddResource(res)
		return converted
	}
	for _, ad := range ads {
		var resByRequest *Resource
		resByAd := NewResource(ad.Resources)
		for _, ps := range qu.Spec.PodSets {
			if ps.Name != ad.Name {
				continue
			}
			specRequests := resourcehelpers.PodRequests(&v1.Pod{Spec: ps.Template.Spec}, resourcehelpers.PodResourcesOptions{})
			res := NewResource(specRequests)
			scaleUp(res, int(ad.Replicas))
			resByRequest = res
			break
		}
		res := max(resByRequest, resByAd)
		converted.Add(res.ResourceList())
	}
	if IsV1VersionDequeued(qu) {
		// 前向兼容
		realtimeRes := NewResource(qu.Spec.Resource)
		for k, v := range realtimeRes.Resources {
			if converted.Resources[k] == 0 {
				converted.Resources[k] = v
			} else if v > converted.Resources[k] {
				converted.Resources[k] = v
			}
		}
	}
	return converted
}

func Add(r1, r2 v1.ResourceList) {
	for k, v := range r2 {
		if _, ok := r1[k]; !ok {
			r1[k] = v.DeepCopy()
			continue
		}
		v1 := r1[k]
		(&v1).Add(v)
		r1[k] = v1
	}
}

func MapCopy[K comparable, V any](m map[K]V) (c map[K]V) {
	c = make(map[K]V, len(m))
	for k, v := range m {
		c[k] = v
	}
	return
}

func SliceCopy[V any](s []V) (c []V) {
	c = make([]V, len(s))
	copy(c, s)
	return
}

func getEndlessRetry() *wait.Backoff {
	return &wait.Backoff{
		Steps:    math.MaxInt64,
		Duration: time.Second,
		Factor:   1.0,
		Jitter:   0.1,
	}
}

func GetAdmissionMap(qu *v1alpha1.QueueUnit) map[string]framework.Admission {
	adMp := make(map[string]framework.Admission)
	for _, ad := range qu.Status.Admissions {
		adMp[ad.Name] = framework.Admission{
			Name:     ad.Name,
			Replicas: ad.Replicas,
		}
	}
	return adMp
}

func GetReservedResource(qu *v1alpha1.QueueUnit) *Resource {
	return ConvertFromStatusAdmissionToResource(qu, qu.Status.Admissions)
}

func TransResourceList(res v1.ResourceList) map[v1.ResourceName]int64 {
	result := make(map[v1.ResourceName]int64)
	for k, v := range res {
		result[k] = v.Value()
	}
	return result
}

func UpdateUsage(a map[v1.ResourceName]int64, b map[v1.ResourceName]int64, m int64) {
	for k, v := range b {
		originV, exist := a[k]
		if !exist {
			a[k] = v * m
			continue
		}
		a[k] = originV + v*m
	}
}

func UpdateQueueUnitStatusAndAnnotations(name string, namespace string, queueName string,
	status *v1alpha1.QueueUnitStatus, client versioned.Interface, annotations map[string]string) (*v1alpha1.QueueUnit, error) {
	var queueUnit *v1alpha1.QueueUnit
	var err error

	err = retry.OnError(*getEndlessRetry(),
		func(err error) bool {
			return errors.IsTooManyRequests(err) || errors.IsConflict(err)
		},
		func() error {
			queueUnit, err = client.SchedulingV1alpha1().QueueUnits(namespace).Get(
				context.Background(), name, metav1.GetOptions{})
			if err != nil {
				klog.Infof("failed to get QueueUnit when try update, QueueUnitName:%v, status:%v", name, status)
				return err
			}

			needUpdateSpec := false
			newQueueUnit := queueUnit.DeepCopy()
			if len(annotations) > 0 {
				for k, v := range annotations {
					if queueUnit.Annotations[k] != v {
						needUpdateSpec = true
						newQueueUnit.Annotations[k] = v
					}
				}
			}
			if queueUnit.Spec.Queue != queueName {
				needUpdateSpec = true
				newQueueUnit.Spec.Queue = queueName
			}

			if needUpdateSpec {
				newQueueUnit, err = client.SchedulingV1alpha1().QueueUnits(namespace).Update(
					context.Background(), newQueueUnit, metav1.UpdateOptions{})
				if err != nil {
					klog.Infof("failed to update QueueUnit, QueueUnitName:%v, status:%v", name, status)
					return err
				}
			}

			if !reflect.DeepEqual(newQueueUnit.Status, *status) {
				newQueueUnit.Status = *status
				queueUnit, err = client.SchedulingV1alpha1().QueueUnits(namespace).UpdateStatus(
					context.Background(), newQueueUnit, metav1.UpdateOptions{})
				if err != nil {
					klog.Infof("failed to update QueueUnit status, QueueUnitName:%v, status:%v", name, status)
				} else {
					klog.Infof("success to update QueueUnit status, QueueUnitName:%v, status:%v", name, status)
				}
			}
			return err
		})

	return queueUnit, err
}

// IsQueueUnitOversold compatible with legacy queue unit, if annotation is empty, we think it is guaranteed
func IsQueueUnitOversold(queueUnit *framework.QueueUnitInfo) bool {
	if queueUnit.Unit.Annotations == nil {
		return false
	}
	if queueUnit.Unit.Annotations[AnnotationActualQuotaOversoldType] == QuotaOversoldTypeForce {
		return true
	}
	return false
}

func GetQueueUnitOversoldAnnotations(annotations map[string]string) (string, string) {
	quotaOversoldType, actualQuotaOversoldType := QuotaOversoldTypeForbidden, QuotaOversoldTypeForbidden
	if annotations != nil {
		quotaOversoldType = annotations[AnnotationQuotaOversoldType]
		actualQuotaOversoldType = annotations[AnnotationActualQuotaOversoldType]
	}

	return quotaOversoldType, actualQuotaOversoldType
}

func IsQueueUnitSuspend(unit *v1alpha1.QueueUnit) bool {
	if unit.Annotations == nil {
		return false
	}
	return unit.Annotations[QueueSuspend] == "true"
}
