/*
Copyright The KunwuLuan Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	apisv1alpha1 "github.com/kube-queue/kube-queue/pkg/visibility/apis/client-go/applyconfiguration/apis/v1alpha1"
	scheme "github.com/kube-queue/kube-queue/pkg/visibility/apis/client-go/clientset/versioned/scheme"
	v1alpha1 "github.com/kube-queue/kube-queue/pkg/visibility/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ElasticQuotasGetter has a method to return a ElasticQuotaInterface.
// A group's client should implement this interface.
type ElasticQuotasGetter interface {
	ElasticQuotas() ElasticQuotaInterface
}

// ElasticQuotaInterface has methods to work with ElasticQuota resources.
type ElasticQuotaInterface interface {
	Create(ctx context.Context, elasticQuota *v1alpha1.ElasticQuota, opts v1.CreateOptions) (*v1alpha1.ElasticQuota, error)
	Update(ctx context.Context, elasticQuota *v1alpha1.ElasticQuota, opts v1.UpdateOptions) (*v1alpha1.ElasticQuota, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ElasticQuota, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ElasticQuotaList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ElasticQuota, err error)
	Apply(ctx context.Context, elasticQuota *apisv1alpha1.ElasticQuotaApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ElasticQuota, err error)
	GetQueueUnitsSummary(ctx context.Context, elasticQuotaName string, options v1.GetOptions) (*v1alpha1.QueueUnitsSummary, error)

	ElasticQuotaExpansion
}

// elasticQuotas implements ElasticQuotaInterface
type elasticQuotas struct {
	*gentype.ClientWithListAndApply[*v1alpha1.ElasticQuota, *v1alpha1.ElasticQuotaList, *apisv1alpha1.ElasticQuotaApplyConfiguration]
}

// newElasticQuotas returns a ElasticQuotas
func newElasticQuotas(c *VisibilityV1alpha1Client) *elasticQuotas {
	return &elasticQuotas{
		gentype.NewClientWithListAndApply[*v1alpha1.ElasticQuota, *v1alpha1.ElasticQuotaList, *apisv1alpha1.ElasticQuotaApplyConfiguration](
			"elasticquotas",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.ElasticQuota { return &v1alpha1.ElasticQuota{} },
			func() *v1alpha1.ElasticQuotaList { return &v1alpha1.ElasticQuotaList{} }),
	}
}

// GetQueueUnitsSummary takes name of the elasticQuota, and returns the corresponding v1alpha1.QueueUnitsSummary object, and an error if there is any.
func (c *elasticQuotas) GetQueueUnitsSummary(ctx context.Context, elasticQuotaName string, options v1.GetOptions) (result *v1alpha1.QueueUnitsSummary, err error) {
	result = &v1alpha1.QueueUnitsSummary{}
	err = c.GetClient().Get().
		Resource("elasticquotas").
		Name(elasticQuotaName).
		SubResource("QueueUnits").
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}
