/*
Copyright The KunwuLuan Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	apisv1alpha1 "github.com/koordinator-sh/koord-queue/pkg/visibility/apis/client-go/applyconfiguration/apis/v1alpha1"
	scheme "github.com/koordinator-sh/koord-queue/pkg/visibility/apis/client-go/clientset/versioned/scheme"
	v1alpha1 "github.com/koordinator-sh/koord-queue/pkg/visibility/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// QueuesGetter has a method to return a QueueInterface.
// A group's client should implement this interface.
type QueuesGetter interface {
	Queues() QueueInterface
}

// QueueInterface has methods to work with Queue resources.
type QueueInterface interface {
	Create(ctx context.Context, queue *v1alpha1.Queue, opts v1.CreateOptions) (*v1alpha1.Queue, error)
	Update(ctx context.Context, queue *v1alpha1.Queue, opts v1.UpdateOptions) (*v1alpha1.Queue, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Queue, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.QueueList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Queue, err error)
	Apply(ctx context.Context, queue *apisv1alpha1.QueueApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Queue, err error)
	GetQueueUnitsSummary(ctx context.Context, queueName string, options v1.GetOptions) (*v1alpha1.QueueUnitsSummary, error)

	QueueExpansion
}

// queues implements QueueInterface
type queues struct {
	*gentype.ClientWithListAndApply[*v1alpha1.Queue, *v1alpha1.QueueList, *apisv1alpha1.QueueApplyConfiguration]
}

// newQueues returns a Queues
func newQueues(c *VisibilityV1alpha1Client) *queues {
	return &queues{
		gentype.NewClientWithListAndApply[*v1alpha1.Queue, *v1alpha1.QueueList, *apisv1alpha1.QueueApplyConfiguration](
			"queues",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.Queue { return &v1alpha1.Queue{} },
			func() *v1alpha1.QueueList { return &v1alpha1.QueueList{} }),
	}
}

// GetQueueUnitsSummary takes name of the queue, and returns the corresponding v1alpha1.QueueUnitsSummary object, and an error if there is any.
func (c *queues) GetQueueUnitsSummary(ctx context.Context, queueName string, options v1.GetOptions) (result *v1alpha1.QueueUnitsSummary, err error) {
	result = &v1alpha1.QueueUnitsSummary{}
	err = c.GetClient().Get().
		Resource("queues").
		Name(queueName).
		SubResource("QueueUnits").
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}
