/*
Copyright The KunwuLuan Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PodStateApplyConfiguration represents a declarative configuration of the PodState type for use
// with apply.
type PodStateApplyConfiguration struct {
	Running *int32 `json:"pending,omitempty"`
	Pending *int32 `json:"running,omitempty"`
}

// PodStateApplyConfiguration constructs a declarative configuration of the PodState type for use with
// apply.
func PodState() *PodStateApplyConfiguration {
	return &PodStateApplyConfiguration{}
}

// WithRunning sets the Running field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Running field is set to the value of the last call.
func (b *PodStateApplyConfiguration) WithRunning(value int32) *PodStateApplyConfiguration {
	b.Running = &value
	return b
}

// WithPending sets the Pending field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pending field is set to the value of the last call.
func (b *PodStateApplyConfiguration) WithPending(value int32) *PodStateApplyConfiguration {
	b.Pending = &value
	return b
}
