/*
Copyright The KunwuLuan Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// QueueUnitApplyConfiguration represents a declarative configuration of the QueueUnit type for use
// with apply.
type QueueUnitApplyConfiguration struct {
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	QuotaName                        *string                     `json:"quotaName,omitempty"`
	QueueName                        *string                     `json:"queueName,omitempty"`
	Request                          map[string]string           `json:"request,omitempty"`
	Resources                        map[string]string           `json:"resources,omitempty"`
	Phase                            *string                     `json:"phase,omitempty"`
	PodState                         *PodStateApplyConfiguration `json:"podState,omitempty"`
}

// QueueUnitApplyConfiguration constructs a declarative configuration of the QueueUnit type for use with
// apply.
func QueueUnit() *QueueUnitApplyConfiguration {
	return &QueueUnitApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithName(value string) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithGenerateName(value string) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithNamespace(value string) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithUID(value types.UID) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithResourceVersion(value string) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithGeneration(value int64) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithCreationTimestamp(value metav1.Time) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *QueueUnitApplyConfiguration) WithLabels(entries map[string]string) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *QueueUnitApplyConfiguration) WithAnnotations(entries map[string]string) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *QueueUnitApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.OwnerReferences = append(b.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *QueueUnitApplyConfiguration) WithFinalizers(values ...string) *QueueUnitApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.Finalizers = append(b.Finalizers, values[i])
	}
	return b
}

func (b *QueueUnitApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithQuotaName sets the QuotaName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QuotaName field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithQuotaName(value string) *QueueUnitApplyConfiguration {
	b.QuotaName = &value
	return b
}

// WithQueueName sets the QueueName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QueueName field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithQueueName(value string) *QueueUnitApplyConfiguration {
	b.QueueName = &value
	return b
}

// WithRequest puts the entries into the Request field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Request field,
// overwriting an existing map entries in Request field with the same key.
func (b *QueueUnitApplyConfiguration) WithRequest(entries map[string]string) *QueueUnitApplyConfiguration {
	if b.Request == nil && len(entries) > 0 {
		b.Request = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Request[k] = v
	}
	return b
}

// WithResources puts the entries into the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Resources field,
// overwriting an existing map entries in Resources field with the same key.
func (b *QueueUnitApplyConfiguration) WithResources(entries map[string]string) *QueueUnitApplyConfiguration {
	if b.Resources == nil && len(entries) > 0 {
		b.Resources = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Resources[k] = v
	}
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithPhase(value string) *QueueUnitApplyConfiguration {
	b.Phase = &value
	return b
}

// WithPodState sets the PodState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodState field is set to the value of the last call.
func (b *QueueUnitApplyConfiguration) WithPodState(value *PodStateApplyConfiguration) *QueueUnitApplyConfiguration {
	b.PodState = value
	return b
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *QueueUnitApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.Name
}
