{
 "title": "AckKoordQueue",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "Namespace",
    "query": {
     "query": "dequeued_quota_usage_by_namespace"
    }
   },
   { "name": "Quota", "query": { "query": "dequeued_quota_usage_by_quota" } },
   { "name": "Resource", "query": { "query": "dequeued_quota_usage_by_quota" } }
  ]
 },
 "panels": [
  { "title": "各Quota资源使用量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "已出队CPU资源量By Quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "dequeued_quota_usage_by_quota{job=\"koord-queue-exporter\",resource=\"cpu\"}/1000",
     "legendFormat": "{{quota}}/资源使用量"
    }
   ]
  },
  {
   "title": "已出队CPU资源量By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dequeued_quota_usage_by_namespace{job=\"koord-queue-exporter\",resource=\"cpu\"}",
     "legendFormat": "{{namespace}}/资源使用量"
    }
   ]
  },
  {
   "title": "已出队Memory资源量By Quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "dequeued_quota_usage_by_quota{job=\"koord-queue-exporter\",resource=\"memory\"}",
     "legendFormat": "{{quota}}/资源使用量"
    }
   ]
  },
  {
   "title": "已出队Memory资源量By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "dequeued_quota_usage_by_namespace{job=\"koord-queue-exporter\",resource=\"memory\"}",
     "legendFormat": "{{namespace}}/资源使用量"
    }
   ]
  },
  {
   "title": "已出队$Resource资源量By Quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "dequeued_quota_usage_by_quota{job=\"koord-queue-exporter\",resource=\"$Resource\",quota=\"$Quota\"}",
     "legendFormat": "{{quota}}/{{resource}}/资源使用量"
    }
   ]
  },
  {
   "title": "出队$Resource资源量By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "dequeued_quota_usage_by_namespace{job=\"koord-queue-exporter\",resource=\"$Resource\", namespace=\"$Namespace\"}",
     "legendFormat": "{{namespace}}/{{resource}}/资源使用量"
    }
   ]
  },
  { "title": "Koord Queue任务数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "KoordQueue各用户任务数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "queueunits_by_job_type{job=\"koord-queue-exporter\"}",
     "legendFormat": "任务数量-{{namespace}}-{{type}}"
    }
   ]
  },
  {
   "title": "KoordQueue各用户任务入队速度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(irate(queueunits_coming_rate_by_job_type{job=\"koord-queue-exporter\", status=\"Enqueued\"}[$interval])) by (namespace)",
     "legendFormat": "入队速度-{{namespace}}"
    },
    {
     "expr": "sum(irate(queueunits_coming_rate_by_job_type{job=\"koord-queue-exporter\", status=\"Enqueued\"}[$interval])) by (namespace, type)",
     "legendFormat": "入队速度-{{namespace}}-{{type}}"
    }
   ]
  },
  {
   "title": "KoordQueue各队列任务数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "queueunits_in_active_queue{job=\"koord-queue-exporter\"}",
     "legendFormat": "{{queue}}/Active队列任务数"
    },
    {
     "expr": "queueunits_in_backoff_queue{job=\"koord-queue-exporter\"}",
     "legendFormat": "{{queue}}/Backoff队列任务数"
    }
   ]
  },
  { "title": "Koord Queue Controller调度指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "KoordQueue调度速度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(job_schedule_attempts{job=\"koord-queue-exporter\",result=\"scheduled\"}[5m])",
     "legendFormat": "成功调度速度"
    },
    {
     "expr": "rate(job_schedule_attempts{job=\"koord-queue-exporter\",result=\"unschedulable\"}[5m])",
     "legendFormat": "调度失败速度"
    }
   ]
  },
  {
   "title": "KoordQueue调度延迟p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(job_scheduling_algorithm_latency_bucket{job=\"koord-queue-exporter\",}[$interval])) by (le))",
     "legendFormat": "调度算法耗时p99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(job_scheduling_e2e_latency_bucket{job=\"koord-queue-exporter\"}[$interval])) by (le))",
     "legendFormat": "端到端耗时p99"
    }
   ]
  },
  { "title": "各组件资源使用量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Ack Koord Queue Controller CPU使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"koord-queue-exporter\"}[$interval])*100"
    }
   ]
  },
  {
   "title": "Ack Kube Controller Memory使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"koord-queue-exporter\"}"
    }
   ]
  },
  {
   "title": "Kube API Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(rest_client_requests_total{job=\"koord-queue-exporter\",code=~\"2..\"}[$interval])) by (method)",
     "legendFormat": "2xx-{{method}}"
    },
    {
     "expr": "sum(irate(rest_client_requests_total{job=\"koord-queue-exporter\",code=~\"3..\"}[$interval])) by (method)",
     "legendFormat": "3xx-{{method}}"
    },
    {
     "expr": "sum(irate(rest_client_requests_total{job=\"koord-queue-exporter\",code=~\"4..\"}[$interval])) by (method)",
     "legendFormat": "4xx-{{method}}"
    },
    {
     "expr": "sum(irate(rest_client_requests_total{job=\"koord-queue-exporter\",code=~\"5..\"}[$interval])) by (method)",
     "legendFormat": "5xx-{{method}}"
    }
   ]
  },
  {
   "title": "Kube API Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"koord-queue-exporter\"}[$interval])) by (verb,le,host))"
    }
   ]
  }
 ]
}