---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pai-priority-1
value: 1
globalDefault: false
preemptionPolicy: Never
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pai-priority-2
value: 2
globalDefault: false
preemptionPolicy: Never
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pai-priority-3
value: 3
globalDefault: false
preemptionPolicy: Never
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pai-priority-4
value: 4
globalDefault: false
preemptionPolicy: Never
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pai-priority-5
value: 5
globalDefault: false
preemptionPolicy: Never
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pai-priority-6
value: 6
globalDefault: false
preemptionPolicy: Never
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pai-priority-7
value: 7
globalDefault: false
preemptionPolicy: Never
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pai-priority-8
value: 8
globalDefault: false
preemptionPolicy: Never
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pai-priority-9
value: 9
globalDefault: false
preemptionPolicy: Never