//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkTopology) DeepCopyInto(out *ClusterNetworkTopology) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkTopology.
func (in *ClusterNetworkTopology) DeepCopy() *ClusterNetworkTopology {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterNetworkTopology) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkTopologyDetailStatus) DeepCopyInto(out *ClusterNetworkTopologyDetailStatus) {
	*out = *in
	out.TopologyInfo = in.TopologyInfo
	out.ParentTopologyInfo = in.ParentTopologyInfo
	if in.ChildTopologyNames != nil {
		in, out := &in.ChildTopologyNames, &out.ChildTopologyNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkTopologyDetailStatus.
func (in *ClusterNetworkTopologyDetailStatus) DeepCopy() *ClusterNetworkTopologyDetailStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkTopologyDetailStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkTopologyList) DeepCopyInto(out *ClusterNetworkTopologyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterNetworkTopology, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkTopologyList.
func (in *ClusterNetworkTopologyList) DeepCopy() *ClusterNetworkTopologyList {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkTopologyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterNetworkTopologyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkTopologySpec) DeepCopyInto(out *ClusterNetworkTopologySpec) {
	*out = *in
	if in.NetworkTopologySpec != nil {
		in, out := &in.NetworkTopologySpec, &out.NetworkTopologySpec
		*out = make([]NetworkTopologySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkTopologySpec.
func (in *ClusterNetworkTopologySpec) DeepCopy() *ClusterNetworkTopologySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkTopologyStatus) DeepCopyInto(out *ClusterNetworkTopologyStatus) {
	*out = *in
	if in.DetailStatus != nil {
		in, out := &in.DetailStatus, &out.DetailStatus
		*out = make([]*ClusterNetworkTopologyDetailStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ClusterNetworkTopologyDetailStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkTopologyStatus.
func (in *ClusterNetworkTopologyStatus) DeepCopy() *ClusterNetworkTopologyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkTopologyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobNetworkTopology) DeepCopyInto(out *JobNetworkTopology) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobNetworkTopology.
func (in *JobNetworkTopology) DeepCopy() *JobNetworkTopology {
	if in == nil {
		return nil
	}
	out := new(JobNetworkTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JobNetworkTopology) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobNetworkTopologyList) DeepCopyInto(out *JobNetworkTopologyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JobNetworkTopology, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobNetworkTopologyList.
func (in *JobNetworkTopologyList) DeepCopy() *JobNetworkTopologyList {
	if in == nil {
		return nil
	}
	out := new(JobNetworkTopologyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JobNetworkTopologyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobNetworkTopologySpec) DeepCopyInto(out *JobNetworkTopologySpec) {
	*out = *in
	if in.TopologyStrategy != nil {
		in, out := &in.TopologyStrategy, &out.TopologyStrategy
		*out = make([]TopologyStrategy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobNetworkTopologySpec.
func (in *JobNetworkTopologySpec) DeepCopy() *JobNetworkTopologySpec {
	if in == nil {
		return nil
	}
	out := new(JobNetworkTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobNetworkTopologyStatus) DeepCopyInto(out *JobNetworkTopologyStatus) {
	*out = *in
	if in.TopologyDetailInfo != nil {
		in, out := &in.TopologyDetailInfo, &out.TopologyDetailInfo
		*out = make([]*TopologyDetailInfo, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TopologyDetailInfo)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobNetworkTopologyStatus.
func (in *JobNetworkTopologyStatus) DeepCopy() *JobNetworkTopologyStatus {
	if in == nil {
		return nil
	}
	out := new(JobNetworkTopologyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkTopologySpec) DeepCopyInto(out *NetworkTopologySpec) {
	*out = *in
	if in.LabelKey != nil {
		in, out := &in.LabelKey, &out.LabelKey
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkTopologySpec.
func (in *NetworkTopologySpec) DeepCopy() *NetworkTopologySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyDetailInfo) DeepCopyInto(out *TopologyDetailInfo) {
	*out = *in
	out.TopologyInfo = in.TopologyInfo
	out.ParentTopologyInfo = in.ParentTopologyInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyDetailInfo.
func (in *TopologyDetailInfo) DeepCopy() *TopologyDetailInfo {
	if in == nil {
		return nil
	}
	out := new(TopologyDetailInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyInfo) DeepCopyInto(out *TopologyInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyInfo.
func (in *TopologyInfo) DeepCopy() *TopologyInfo {
	if in == nil {
		return nil
	}
	out := new(TopologyInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyStrategy) DeepCopyInto(out *TopologyStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyStrategy.
func (in *TopologyStrategy) DeepCopy() *TopologyStrategy {
	if in == nil {
		return nil
	}
	out := new(TopologyStrategy)
	in.DeepCopyInto(out)
	return out
}
