package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	ImageStatusCommitting  = "Committing"
	ImageStatusSaved       = "Saved"
	ImageStatusFailed      = "Failed"
	ImageStatusPushing     = "Pushing"
	ImageStatusInitialized = "Initialized"
)

const (
	// Push to dsw system acr(aliyun container registry)
	RegistryTypeSystem = "system"
	// Push to user specified acr
	RegistryTypeUser = "user"
)

// ImageSpec defines the desired state of Image
type ImageSpec struct {
	// UserId (aliyun pk)
	UserId string `json:"userId,omitempty"`

	// The ACR Registry information
	AcrRegistryInfo *AcrRegistryInfo `json:"acrRegistryInfo,omitempty"`

	// Docker repository
	DockerRepository string `json:"dockerRepository,omitempty"`

	// Docker Image Version
	DockerImageVersion string `json:"dockerImageVersion,omitempty"`

	// +optional
	SaveTime *metav1.Time `json:"saveTime,omitempty"`

	// ImageId is used when saving instance, which records the image id in DB
	// +optional
	ImageId int64 `json:"imageId,omitempty"`
}

type AcrRegistryInfo struct {
	// If "" then push to default acr instance
	// Else push to CR enterprise acr instance
	InstanceId string `json:"instanceId,omitempty"`
	// Registry type: such as "system", "user"
	RegistryType string `json:"registryType,omitempty"`
}

// ImageStatus defines the observed state of Image
type ImageStatus struct {
	// Information when was the last time the image was updated.
	// +optional
	LastUpdateTime *metav1.Time `json:"lastUpdateTime,omitempty"`
	// The last processed imageId generated by db
	// +optional
	LastProcessedImageId int64 `json:"lastProcessedImageId,omitempty"`
	// The last docker image version after image successfully committed && pushed
	// +optional
	LastDockerImageVersion string `json:"lastDockerImageVersion,omitempty"`
	// Current docker image save phase
	// +optional
	Status string `json:"status,omitempty"`
	// Current docker image save error message
	// +optional
	Message string `json:"message,omitempty"`
	// Docker image save history
	// +optional
	ImageSaveHistory []ImageSaveHistory `json:"imageSaveHistory,omitempty"`
}

type ImageSaveHistory struct {
	// Information when was the last time the image was updated
	// +optional
	UpdateTime *metav1.Time `json:"updateTime,omitempty"`
	// The imageId generated by db
	// +optional
	SavedImageId int64 `json:"savedImageId,omitempty"`
	// The docker image version after image successfully committed && pushed
	// +optional
	DockerImageVersion string `json:"dockerImageVersion,omitempty"`
	// The docker image url after image successfully committed && pushed
	// +optional
	SavedImageUrl string `json:"savedImageUrl,omitempty"`
	// Docker image save status
	// +optional
	DockerImageSaveStatus string `json:"dockerImageSaveStatus,omitempty"`
	// Docker image save error message
	// +optional
	Message string `json:"message,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:JSONPath=".status.status",name=Status,type=string
// +kubebuilder:printcolumn:JSONPath=".status.message",name=Message,type=string
// +kubebuilder:printcolumn:JSONPath=".metadata.creationTimestamp",name=Age,type=date
// +genclient

type Image struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ImageSpec   `json:"spec,omitempty"`
	Status ImageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ImageList contains a list of Image
type ImageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Image `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Image{}, &ImageList{})
}
