package v1

import (
	"fmt"

	"github.com/koordinator-sh/koord-queue/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	"k8s.io/apimachinery/pkg/runtime"
)

// Convert_v1_KoordQueueConfiguration_To_config_KoordQueueConfiguration is an autogenerated conversion function.
func Convert_v1_KoordQueueConfiguration_To_config_KoordQueueConfiguration(in *KoordQueueConfiguration, out *config.KoordQueueConfiguration, s conversion.Scope) error {
	if err := autoConvert_v1_KoordQueueConfiguration_To_config_KoordQueueConfiguration(in, out, s); err != nil {
		return err
	}

	scheme := runtime.NewScheme()
	localSchemeBuilder.AddToScheme(scheme)
	config.AddToScheme(scheme)
	for name, pluginConfig := range out.PluginConfigs {
		if pluginConfig == nil {
			continue
		}
		if _, isUnknown := pluginConfig.(*runtime.Unknown); isUnknown {
			continue
		}
		internalArgs, err := scheme.ConvertToVersion(pluginConfig, config.SchemeGroupVersion)
		if err != nil {
			return fmt.Errorf("converting .PluginConfig[%s] into internal type: %w", name, err)
		}
		out.PluginConfigs[name] = internalArgs
	}
	return nil
}

// Convert_config_KoordQueueConfiguration_To_v1_KoordQueueConfiguration is an autogenerated conversion function.
func Convert_config_KoordQueueConfiguration_To_v1_KoordQueueConfiguration(in *config.KoordQueueConfiguration, out *KoordQueueConfiguration, s conversion.Scope) error {
	if err := autoConvert_config_KoordQueueConfiguration_To_v1_KoordQueueConfiguration(in, out, s); err != nil {
		return err
	}

	scheme := runtime.NewScheme()
	localSchemeBuilder.AddToScheme(scheme)
	config.AddToScheme(scheme)
	for name, pluginConfig := range out.PluginConfigs {
		if pluginConfig.Object == nil {
			continue
		}
		if _, isUnknown := pluginConfig.Object.(*runtime.Unknown); isUnknown {
			continue
		}
		internalArgs, err := scheme.ConvertToVersion(pluginConfig.Object, SchemeGroupVersion)
		if err != nil {
			return fmt.Errorf("converting .PluginConfig[%s] into v1 type: %w", name, err)
		}
		pluginConfig.Object = internalArgs
		out.PluginConfigs[name] = pluginConfig
	}
	return nil
}
