//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	config "github.com/koordinator-sh/koord-queue/pkg/apis/config"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*config.ElasticQuotaArgs)(nil), (*ElasticQuotaArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ElasticQuotaArgs_To_v1_ElasticQuotaArgs(a.(*config.ElasticQuotaArgs), b.(*ElasticQuotaArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ElasticQuotaArgs)(nil), (*config.ElasticQuotaArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ElasticQuotaArgs_To_config_ElasticQuotaArgs(a.(*ElasticQuotaArgs), b.(*config.ElasticQuotaArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Plugin)(nil), (*Plugin)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Plugin_To_v1_Plugin(a.(*config.Plugin), b.(*Plugin), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Plugin)(nil), (*config.Plugin)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Plugin_To_config_Plugin(a.(*Plugin), b.(*config.Plugin), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*config.KoordQueueConfiguration)(nil), (*KoordQueueConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_KoordQueueConfiguration_To_v1_KoordQueueConfiguration(a.(*config.KoordQueueConfiguration), b.(*KoordQueueConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*KoordQueueConfiguration)(nil), (*config.KoordQueueConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_KoordQueueConfiguration_To_config_KoordQueueConfiguration(a.(*KoordQueueConfiguration), b.(*config.KoordQueueConfiguration), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_config_ElasticQuotaArgs_To_v1_ElasticQuotaArgs(in *config.ElasticQuotaArgs, out *ElasticQuotaArgs, s conversion.Scope) error {
	if err := metav1.Convert_bool_To_Pointer_bool(&in.CheckQuotaOversold, &out.CheckQuotaOversold, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_ElasticQuotaArgs_To_v1_ElasticQuotaArgs is an autogenerated conversion function.
func Convert_config_ElasticQuotaArgs_To_v1_ElasticQuotaArgs(in *config.ElasticQuotaArgs, out *ElasticQuotaArgs, s conversion.Scope) error {
	return autoConvert_config_ElasticQuotaArgs_To_v1_ElasticQuotaArgs(in, out, s)
}

func autoConvert_v1_ElasticQuotaArgs_To_config_ElasticQuotaArgs(in *ElasticQuotaArgs, out *config.ElasticQuotaArgs, s conversion.Scope) error {
	if err := metav1.Convert_Pointer_bool_To_bool(&in.CheckQuotaOversold, &out.CheckQuotaOversold, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ElasticQuotaArgs_To_config_ElasticQuotaArgs is an autogenerated conversion function.
func Convert_v1_ElasticQuotaArgs_To_config_ElasticQuotaArgs(in *ElasticQuotaArgs, out *config.ElasticQuotaArgs, s conversion.Scope) error {
	return autoConvert_v1_ElasticQuotaArgs_To_config_ElasticQuotaArgs(in, out, s)
}

func autoConvert_config_KoordQueueConfiguration_To_v1_KoordQueueConfiguration(in *config.KoordQueueConfiguration, out *KoordQueueConfiguration, s conversion.Scope) error {
	if in.PluginConfigs != nil {
		in, out := &in.PluginConfigs, &out.PluginConfigs
		*out = make(map[string]runtime.RawExtension, len(*in))
		for key, val := range *in {
			newVal := new(runtime.RawExtension)
			if err := runtime.Convert_runtime_Object_To_runtime_RawExtension(&val, newVal, s); err != nil {
				return err
			}
			(*out)[key] = *newVal
		}
	} else {
		out.PluginConfigs = nil
	}
	out.Plugins = *(*[]Plugin)(unsafe.Pointer(&in.Plugins))
	return nil
}

func autoConvert_v1_KoordQueueConfiguration_To_config_KoordQueueConfiguration(in *KoordQueueConfiguration, out *config.KoordQueueConfiguration, s conversion.Scope) error {
	if in.PluginConfigs != nil {
		in, out := &in.PluginConfigs, &out.PluginConfigs
		*out = make(map[string]runtime.Object, len(*in))
		for key, val := range *in {
			newVal := new(runtime.Object)
			if err := runtime.Convert_runtime_RawExtension_To_runtime_Object(&val, newVal, s); err != nil {
				return err
			}
			(*out)[key] = *newVal
		}
	} else {
		out.PluginConfigs = nil
	}
	out.Plugins = *(*[]config.Plugin)(unsafe.Pointer(&in.Plugins))
	return nil
}

func autoConvert_config_Plugin_To_v1_Plugin(in *config.Plugin, out *Plugin, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_config_Plugin_To_v1_Plugin is an autogenerated conversion function.
func Convert_config_Plugin_To_v1_Plugin(in *config.Plugin, out *Plugin, s conversion.Scope) error {
	return autoConvert_config_Plugin_To_v1_Plugin(in, out, s)
}

func autoConvert_v1_Plugin_To_config_Plugin(in *Plugin, out *config.Plugin, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1_Plugin_To_config_Plugin is an autogenerated conversion function.
func Convert_v1_Plugin_To_config_Plugin(in *Plugin, out *config.Plugin, s conversion.Scope) error {
	return autoConvert_v1_Plugin_To_config_Plugin(in, out, s)
}
